INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('2000-01-15', 'Gómez', 'La Floresta', 'Quito', 'Tecnología Superior en Big Data', '1712345670', '1ro', 'Av. Amazonas', 'Soltero', 'masculino', 'Quito', 'Juan', 'Ecuador', 'Centro Histórico', 'Estudiante', 'Pichincha', '0987654320', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1985-11-23', 'Gómez', 'El Bosque', 'Guayaquil', 'Desarrollo de Software', '0923456788', '2do', 'Calle Primera', 'Casado', 'femenino', 'Guayaquil', 'Ana', 'Ecuador', 'La Alborada', 'Profesor', 'Guayas', '0976543211', 'O+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1992-05-10', 'Pérez', 'La Carolina', 'Quito', 'Tributación', '1734567891', '3ero', 'Av. República', 'Soltero', 'masculino', 'Quito', 'Carlos', 'Ecuador', 'La Mariscal', 'Estudiante', 'Pichincha', '0998765433', 'B+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1989-12-05', 'Mendoza', 'La Carolina', 'Quito', 'Ciberseguridad', '1734567892', '4to', 'Av. República', 'Divorciado', 'femenino', 'Quito', 'Sofía', 'Ecuador', 'La Mariscal', 'Profesor', 'Pichincha', '0998765434', 'AB+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1994-03-20', 'Ramírez', 'San Carlos', 'Esmeraldas', 'Entrenamiento Deportivo', '0957890124', '5to', 'Av. Esmeraldas', 'Soltero', 'masculino', 'Esmeraldas', 'Luis', 'Ecuador', 'San Rafael', 'Estudiante', 'Esmeraldas', '0984321098', 'O-');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1991-08-15', 'Rodríguez', 'El Batán', 'Loja', 'Desarrollo de Software', '0946789013', '1ro', 'Calle Loja', 'Casada', 'femenino', 'Loja', 'María', 'Ecuador', 'Punzara', 'Estudiante', 'Loja', '0975432110', 'A-');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1997-04-04', 'Ramírez', 'La Victoria', 'Portoviejo', 'Ciberseguridad', '0968901235', '2do', 'Calle Portoviejo', 'Soltero', 'masculino', 'Portoviejo', 'Ricardo', 'Ecuador', 'Santa Ana', 'Estudiante', 'Manabí', '0995432109', 'B-');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1993-05-18', 'Gómez', 'La Floresta', 'Quito', 'Entrenamiento Deportivo', '1712345671', '3ero', 'Av. Amazonas', 'Casado', 'femenino', 'Quito', 'Lucía', 'Ecuador', 'Centro Histórico', 'Profesor', 'Pichincha', '0987654322', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1988-07-25', 'Lopez', 'San Juan', 'Cuenca', 'Tributación', '0935678902', '4to', 'Calle Larga', 'Viudo', 'masculino', 'Cuenca', 'Mario', 'Ecuador', 'El Vecino', 'Profesor', 'Azuay', '0964321100', 'O+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1995-10-10', 'Martínez', 'La Victoria', 'Portoviejo', 'Desarrollo de Software', '0968901236', '5to', 'Calle Portoviejo', 'Soltero', 'masculino', 'Portoviejo', 'Andrés', 'Ecuador', 'Santa Ana', 'Estudiante', 'Manabí', '0995432111', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1990-02-20', 'Vargas', 'Los Chillos', 'Sangolquí', 'Tecnología Superior en Big Data', '0979012346', '1ro', 'Calle General', 'Soltera', 'femenino', 'Sangolquí', 'Laura', 'Ecuador', 'San Rafael', 'Estudiante', 'Pichincha', '0976543220', 'AB+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1994-12-01', 'Gómez', 'El Bosque', 'Guayaquil', 'Ciberseguridad', '0923456787', '2do', 'Calle Segunda', 'Casado', 'masculino', 'Guayaquil', 'Fernando', 'Ecuador', 'La Alborada', 'Estudiante', 'Guayas', '0976543212', 'O-');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1998-05-25', 'Rodríguez', 'San Carlos', 'Esmeraldas', 'Entrenamiento Deportivo', '0957890125', '3ero', 'Av. Esmeraldas', 'Soltera', 'femenino', 'Esmeraldas', 'Valeria', 'Ecuador', 'San Rafael', 'Estudiante', 'Esmeraldas', '0984321101', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1986-11-10', 'Pérez', 'La Carolina', 'Quito', 'Tributación', '1734567893', '4to', 'Av. República', 'Casado', 'masculino', 'Quito', 'Pedro', 'Ecuador', 'La Mariscal', 'Profesor', 'Pichincha', '0998765435', 'B-');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1983-09-18', 'Mendoza', 'La Carolina', 'Quito', 'Tecnología Superior en Big Data', '1734567894', '2do', 'Av. República', 'Divorciado', 'femenino', 'Quito', 'Paola', 'Ecuador', 'La Mariscal', 'Profesor', 'Pichincha', '0998765436', 'AB+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1996-11-05', 'Ramírez', 'San Carlos', 'Esmeraldas', 'Entrenamiento Deportivo', '0957890126', '5to', 'Av. Esmeraldas', 'Soltero', 'masculino', 'Esmeraldas', 'Diego', 'Ecuador', 'San Rafael', 'Estudiante', 'Esmeraldas', '0984321102', 'O+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1988-01-15', 'Rodríguez', 'El Batán', 'Loja', 'Desarrollo de Software', '0946789014', '1ro', 'Calle Loja', 'Casada', 'femenino', 'Loja', 'Ana', 'Ecuador', 'Punzara', 'Estudiante', 'Loja', '0975432112', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1995-06-10', 'Gómez', 'La Floresta', 'Quito', 'Tecnología Superior en Big Data', '1712345672', '2do', 'Av. Amazonas', 'Soltero', 'masculino', 'Quito', 'David', 'Ecuador', 'Centro Histórico', 'Estudiante', 'Pichincha', '0987654323', 'B+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1989-11-25', 'Pérez', 'San Juan', 'Cuenca', 'Tributación', '0935678903', '3ero', 'Calle Larga', 'Casado', 'masculino', 'Cuenca', 'Hugo', 'Ecuador', 'El Vecino', 'Profesor', 'Azuay', '0964321103', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1990-10-15', 'Ramírez', 'La Victoria', 'Portoviejo', 'Desarrollo de Software', '0968901237', '1ro', 'Calle Portoviejo', 'Soltero', 'masculino', 'Portoviejo', 'Tomás', 'Ecuador', 'Santa Ana', 'Estudiante', 'Manabí', '0995432113', 'B+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1987-12-30', 'Gómez', 'El Bosque', 'Guayaquil', 'Entrenamiento Deportivo', '0923456789', '4to', 'Calle Primera', 'Casada', 'femenino', 'Guayaquil', 'Clara', 'Ecuador', 'La Alborada', 'Profesor', 'Guayas', '0976543214', 'A+');
INSERT INTO `paciente`(`fecha_nacimiento_pac`, `apellido_pac`, `barrio_pac`, `canton_pac`, `carrera_pac`, `cedula_pac`, `ciclo_pac`, `direccion_pac`, `estado_civil_pac`, `genero_pac`, `lugar_pac`, `nombre_pac`, `pais_pac`, `parroquia_pac`, `profesion_pac`, `provincia_pac`, `telefono_pac`, `tipo_sangre_pac`) VALUES ('1996-04-15', 'Vargas', 'Los Chillos', 'Sangolquí', 'Ciberseguridad', '0979012347', '2do', 'Calle General', 'Soltera', 'femenino', 'Sangolquí', 'Daniela', 'Ecuador', 'San Rafael', 'Estudiante', 'Pichincha', '0976543221', 'AB+');


INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (FALSE, 20.0, 'Visual', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (TRUE, 50.0, 'Cognitiva', TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (TRUE, 30.0, 'Auditiva',  TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( FALSE, 10.0, 'Física leve',TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (FALSE, 40.0, 'Motora', TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( TRUE, 70.0, 'Intelectual severa', TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (TRUE, 60.0, 'Auditiva y Visual',TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( FALSE, 25.0, 'Física moderada', TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (FALSE, 80.0, 'Parálisis', TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( TRUE, 90.0, 'Cognitiva avanzada', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( FALSE, 15.0, 'Física leve', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (TRUE, 35.0, 'Física e Intelectual', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( TRUE, 55.0, 'Dislexia', TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (FALSE, 50.0, 'Amputación', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( FALSE, 30.0, 'Física moderada', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (TRUE, 45.0, 'Física y Auditiva',  TRUE,'12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( TRUE, 75.0, 'Autismo', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (FALSE, 65.0, 'Parálisis parcial', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( FALSE, 20.0, 'Física leve', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (TRUE, 40.0, 'Física e Intelectual severa', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES ( TRUE, 85.0, 'Síndrome de Down', TRUE, '12345');
INSERT INTO `discapacidad`(`discapacidadg`, `porcentaje_dis`, `subtipo_dis`, `carnet_con`, `numero_conadis`) VALUES (FALSE, 90.0, 'Parálisis completa', TRUE, '12345');


INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, FALSE, TRUE, FALSE, TRUE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, FALSE, TRUE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, TRUE, FALSE, FALSE, TRUE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, FALSE, TRUE, TRUE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, FALSE, TRUE, TRUE, FALSE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, TRUE, TRUE, FALSE, TRUE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, FALSE, TRUE, FALSE, TRUE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, TRUE, FALSE, TRUE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, TRUE, FALSE, TRUE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, FALSE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, TRUE, TRUE, FALSE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, TRUE, TRUE, TRUE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, FALSE, FALSE, TRUE, TRUE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, TRUE, FALSE, FALSE, TRUE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, TRUE, FALSE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, FALSE, TRUE, TRUE, TRUE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, FALSE, TRUE, TRUE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, TRUE, TRUE, FALSE, FALSE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, FALSE, TRUE, TRUE, FALSE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (TRUE, FALSE, TRUE, FALSE, TRUE, TRUE);
INSERT INTO `antecedente_familiar` (`alergia_ant`, `clinico_ant`, `ginecologo_ant`, `traumatologico_ant`, `quirurgico_ant`, `farmacologico_ant`) VALUES (FALSE, TRUE, TRUE, TRUE, FALSE, TRUE);


INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (1, 1, 1, '2024-01-01');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (2, 2, 2, '2024-01-02');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (3, 3, 3, '2024-01-03');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (4, 4, 4, '2024-01-04');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (5, 5, 5, '2024-01-05');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (6, 6, 6, '2024-01-06');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (7, 7, 7, '2024-01-07');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (8, 8, 8, '2024-01-08');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (9, 9, 9, '2024-01-09');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (10, 10, 10, '2024-01-10');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (11, 11, 11, '2024-01-11');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (12, 12, 12, '2024-01-12');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (13, 13, 13, '2024-01-13');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (14, 14, 14, '2024-01-14');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (15, 15, 15, '2024-01-15');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (16, 16, 16, '2024-01-16');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (17, 17, 17, '2024-01-17');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (18, 18, 18, '2024-01-18');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (19, 19, 19, '2024-01-19');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (20, 20, 20, '2024-01-20');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (21, 21, 21, '2024-01-21');
INSERT INTO `ficha_medica` (`fk_id_pac`, `fk_id_dis`, `fk_id_ant`, `fecha_elaboracion_fic`) VALUES (22, 22, 22, '2024-01-22');


INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030405', 'Juan', 'Pérez', '0987654321', 'Av. 10 de Agosto 123', 'Cardiología', 'ABC123', 'Masculino', 'password123');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030406', 'María', 'García', '0998765432', 'Calle 12 de Octubre 45', 'Pediatría', 'XYZ789', 'Femenino', 'securepassword');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030407', 'Luis', 'Martínez', '0976543210', 'Av. de la República 678', 'Oftalmología', 'LMN456', 'Masculino', 'mypassword');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030408', 'Ana', 'Fernández', '0965432109', 'Calle Bolívar 32', 'Dermatología', 'DEF123', 'Femenino', 'password456');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030409', 'Carlos', 'López', '0954321098', 'Av. Amazonas 789', 'Traumatología', 'GHI789', 'Masculino', 'secure456');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030410', 'Laura', 'Torres', '0943210987', 'Calle Sucre 11', 'Ginecología', 'JKL234', 'Femenino', 'mypassword789');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030411', 'Pedro', 'Mendoza', '0932109876', 'Av. 6 de Diciembre 234', 'Neurocirugía', 'MNO345', 'Masculino', 'password789');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030412', 'Sofía', 'Ramos', '0921098765', 'Calle García Moreno 56', 'Medicina General', 'PQR456', 'Femenino', 'secure789');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030413', 'Ricardo', 'González', '0910987654', 'Av. 9 de Octubre 78', 'Endocrinología', 'STU567', 'Masculino', 'mypassword123');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030414', 'Claudia', 'Vásquez', '0909876543', 'Calle 24 de Mayo 90', 'Psiquiatría', 'VWX678', 'Femenino', 'password123');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030415', 'Gabriel', 'Pérez', '0987654321', 'Calle Eloy Alfaro 123', 'Oftalmología', 'YZA789', 'Masculino', 'secure123');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030416', 'María', 'Salazar', '0976543210', 'Av. 10 de Agosto 234', 'Cardiología', 'BCD890', 'Femenino', 'mypassword456');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030417', 'Fernando', 'Márquez', '0965432108', 'Calle Rumiñahui 345', 'Pediatría', 'EFG901', 'Masculino', 'password321');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030418', 'Isabela', 'Morales', '0954321097', 'Av. 12 de Octubre 456', 'Oncología', 'HIJ012', 'Femenino', 'secure789');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030419', 'Luis', 'Hernández', '0943210986', 'Calle Bolívar 678', 'Reumatología', 'KLM123', 'Masculino', 'mypassword789');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030420', 'Natalia', 'Castro', '0932109875', 'Av. 24 de Mayo 789', 'Nefrología', 'NOP234', 'Femenino', 'password456');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030421', 'Jorge', 'Gómez', '0921098764', 'Calle Olmedo 890', 'Dermatología', 'QRS345', 'Masculino', 'secure456');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030422', 'Andrea', 'Paredes', '0910987653', 'Av. Amazonas 901', 'Ginecología', 'TUV456', 'Femenino', 'mypassword123');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030423', 'Oscar', 'Romero', '0909876542', 'Calle Sucre 012', 'Neurocirugía', 'WXY567', 'Masculino', 'password789');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030424', 'Valeria', 'García', '0898765431', 'Av. 9 de Octubre 123', 'Medicina General', 'ZAB678', 'Femenino', 'secure123');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030425', 'Ricardo', 'Castillo', '0887654320', 'Calle García Moreno 234', 'Endocrinología', 'CDE789', 'Masculino', 'mypassword456');
INSERT INTO `doctor` (`cedula_doc`, `nombre_doc`, `apellido_doc`, `telefono_doc`, `direccion_doc`, `especialidad_doc`, `codigo_msp_doc`, `genero_doc`, `password_doc`) VALUES ('0102030426', 'Camila', 'Benítez', '0876543219', 'Av. 6 de Diciembre 345', 'Psiquiatría', 'EFG890', 'Femenino', 'password321');


INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Instituto Nacional', 'Av. de los Pinos 123', 'Dr. Juan Pérez', 'BASE64_ENCODED_IMAGE_1');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Universidad Central', 'Calle de la Paz 456', 'Dra. Ana López', 'BASE64_ENCODED_IMAGE_2');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Colegio de Ciencias', 'Av. 10 de Agosto 789', 'Dr. Carlos González', 'BASE64_ENCODED_IMAGE_3');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Academia de Artes', 'Calle Ecuador 234', 'Dra. Isabel Torres', 'BASE64_ENCODED_IMAGE_4');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Instituto de Tecnología', 'Av. Libertador 567', 'Dr. Luis Morales', 'BASE64_ENCODED_IMAGE_5');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Centro de Estudios', 'Calle Bolívar 890', 'Dra. María García', 'BASE64_ENCODED_IMAGE_6');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Escuela de Negocios', 'Av. Amazonas 123', 'Dr. Fernando Ruiz', 'BASE64_ENCODED_IMAGE_7');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Instituto Superior', 'Calle Colón 456', 'Dra. Laura Méndez', 'BASE64_ENCODED_IMAGE_8');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Universidad Técnica', 'Av. 24 de Mayo 789', 'Dr. Miguel Fernández', 'BASE64_ENCODED_IMAGE_9');
INSERT INTO `instituto` (`nombre_ins`, `direccion_ins`, `rector_ins`, `image_instituto`) VALUES ('Academia de Ciencias', 'Calle Sucre 012', 'Dra. Claudia Sánchez', 'BASE64_ENCODED_IMAGE_10');


INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E013', 'Insuficiencia Cardíaca', 'Cardiovascular', 'Condición en la que el corazón no puede bombear sangre de manera eficiente.', 'Fatiga, hinchazón en las piernas, dificultad para respirar.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E014', 'EPOC', 'Respiratoria', 'Enfermedad pulmonar obstructiva crónica que causa flujo de aire obstruido desde los pulmones.', 'Tos crónica, dificultad para respirar, producción de esputo.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E015', 'Parkinson', 'Neurológica', 'Trastorno del sistema nervioso que afecta el movimiento.', 'Temblores, rigidez muscular, lentitud de movimientos.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E016', 'Alzheimer', 'Neurológica', 'Enfermedad neurodegenerativa que causa problemas con la memoria, el pensamiento y el comportamiento.', 'Pérdida de memoria, confusión, cambios de comportamiento.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E017', 'Osteoporosis', 'Ósea', 'Condición que debilita los huesos, haciéndolos frágiles y más propensos a romperse.', 'Dolor de espalda, pérdida de estatura, fracturas óseas.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E018', 'Anemia', 'Hematológica', 'Condición en la que no hay suficientes glóbulos rojos sanos para transportar oxígeno adecuadamente a los tejidos del cuerpo.', 'Fatiga, debilidad, piel pálida.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E019', 'Esquizofrenia', 'Psiquiátrica', 'Trastorno mental grave que afecta la capacidad de una persona para pensar, sentir y comportarse con claridad.', 'Alucinaciones, delirios, trastornos del pensamiento.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E020', 'Obesidad', 'Metabólica', 'Condición médica en la que el exceso de grasa corporal puede afectar la salud.', 'Aumento de peso, fatiga, dificultad para respirar.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E021', 'Diabetes Tipo 1', 'Metabólica', 'Enfermedad crónica en la que el páncreas produce poca o ninguna insulina.', 'Sed excesiva, hambre extrema, pérdida de peso.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E022', 'Diabetes Tipo 2', 'Metabólica', 'Trastorno en el cual el cuerpo no utiliza insulina de manera adecuada.', 'Sed excesiva, micción frecuente, fatiga.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E023', 'Artritis Reumatoide', 'Autoinmune', 'Trastorno inflamatorio crónico que afecta las articulaciones.', 'Dolor en las articulaciones, hinchazón, rigidez matutina.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E024', 'Lupus', 'Autoinmune', 'Enfermedad autoinmune que causa inflamación en diferentes partes del cuerpo.', 'Fatiga, dolor en las articulaciones, erupciones cutáneas.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E025', 'Asma', 'Respiratoria', 'Enfermedad crónica que inflama y estrecha las vías respiratorias.', 'Dificultad para respirar, sibilancias, tos.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E026', 'Hipertensión', 'Cardiovascular', 'Condición en la que la fuerza de la sangre contra las paredes de las arterias es demasiado alta.', 'Dolor de cabeza, mareos, visión borrosa.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E027', 'Hepatitis B', 'Infecciosa', 'Infección viral que causa inflamación del hígado.', 'Ictericia, fatiga, dolor abdominal.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E028', 'Hepatitis C', 'Infecciosa', 'Infección viral que causa inflamación del hígado y puede llevar a daño hepático grave.', 'Fatiga, fiebre, dolor en las articulaciones.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E029', 'COVID-19', 'Infecciosa', 'Enfermedad causada por el coronavirus SARS-CoV-2.', 'Fiebre, tos, dificultad para respirar.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E030', 'Migraña', 'Neurológica', 'Dolor de cabeza recurrente e intenso que puede causar náuseas y sensibilidad a la luz.', 'Dolor de cabeza severo, náuseas, sensibilidad a la luz.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E031', 'Esclerosis Múltiple', 'Neurológica', 'Enfermedad crónica que afecta el sistema nervioso central.', 'Fatiga, problemas de equilibrio, visión borrosa.');
INSERT INTO `enfermedad` (`codigo_enf`, `nombre_enf`, `tipo_enf`, `descripcion_enf`, `sintomas_enf`) VALUES ('E032', 'Enfermedad Celíaca', 'Autoinmune', 'Trastorno en el cual la ingestión de gluten daña el intestino delgado.', 'Diarrea, dolor abdominal, pérdida de peso.');


INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 1', 'Enfermedad 1', 'Tratamiento 1', 1, 1, '2024-07-01');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 2', 'Enfermedad 2', 'Tratamiento 2', 2, 2, '2024-07-02');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 3', 'Enfermedad 3', 'Tratamiento 3', 3, 3, '2024-07-03');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 4', 'Enfermedad 4', 'Tratamiento 4', 4, 4, '2024-07-04');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 5', 'Enfermedad 5', 'Tratamiento 5', 5, 5, '2024-07-05');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 6', 'Enfermedad 6', 'Tratamiento 6', 6, 6, '2024-07-06');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 7', 'Enfermedad 7', 'Tratamiento 7', 7, 7, '2024-07-07');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 8', 'Enfermedad 8', 'Tratamiento 8', 8, 8, '2024-07-08');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 9', 'Enfermedad 9', 'Tratamiento 9', 9, 9, '2024-07-09');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 10', 'Enfermedad 10', 'Tratamiento 10', 10, 10, '2024-07-10');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 11', 'Enfermedad 11', 'Tratamiento 11', 11, 11, '2024-07-11');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 12', 'Enfermedad 12', 'Tratamiento 12', 12, 12, '2024-07-12');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 13', 'Enfermedad 13', 'Tratamiento 13', 13, 13, '2024-07-13');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 14', 'Enfermedad 14', 'Tratamiento 14', 14, 14, '2024-07-14');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 15', 'Enfermedad 15', 'Tratamiento 15', 15, 15, '2024-07-15');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 16', 'Enfermedad 16', 'Tratamiento 16', 16, 16, '2024-07-16');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 17', 'Enfermedad 17', 'Tratamiento 17', 17, 17, '2024-07-17');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 18', 'Enfermedad 18', 'Tratamiento 18', 18, 18, '2024-07-18');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 19', 'Enfermedad 19', 'Tratamiento 19', 19, 19, '2024-07-19');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 20', 'Enfermedad 20', 'Tratamiento 20', 20, 20, '2024-07-20');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 21', 'Enfermedad 21', 'Tratamiento 21', 21, 21, '2024-07-21');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 22', 'Enfermedad 22', 'Tratamiento 22', 22, 22, '2024-07-22');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 23', 'Enfermedad 23', 'Tratamiento 23', 1, 1, '2024-07-23');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 24', 'Enfermedad 24', 'Tratamiento 24', 2, 2, '2024-07-24');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 25', 'Enfermedad 25', 'Tratamiento 25', 3, 3, '2024-07-25');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 26', 'Enfermedad 26', 'Tratamiento 26', 4, 4,'2024-07-26');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 27', 'Enfermedad 27', 'Tratamiento 27', 5, 5, '2024-07-27');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 28', 'Enfermedad 28', 'Tratamiento 28', 6, 6, '2024-07-28');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 29', 'Enfermedad 29', 'Tratamiento 29', 7, 7, '2024-07-29');
INSERT INTO `atencion_medica` (`motivo_ate`, `enfermedad_actual_ate`, `tratamiento_ate`, `fk_id_ficha_medica`, `fk_id_doctor`, `fecha_atencion_ate`) VALUES ('Motivo 30', 'Enfermedad 30', 'Tratamiento 30', 8, 8, '2024-07-30');


INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('PA', 'mmHg');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('PESO', 'kg');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('TALLA', 'cm');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('IMC', 'kg/m2');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('FC', 'bpm');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('FR', 'rpm');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('T', '°C');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('SatO2', '%');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('GLASGOW', 'puntos');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('OCULAR', 'puntos');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('VERBAL', 'puntos');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('MOTORA', 'puntos');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('TOTAL', 'puntos');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('LLENADO_CAPILAR', 'segundos');
INSERT INTO signo_vital (nombre_sig, unidad_sig) VALUES ('R_PUPILAR', 'puntos');


INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (120.0, 1, 1);  -- PA
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (70.0, 1, 2);   -- PESO
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (170.0, 1, 3);  -- TALLA
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (24.2, 1, 4);   -- IMC
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (75.0, 1, 5);   -- FC
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (18.0, 1, 6);   -- FR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (36.5, 1, 7);   -- T
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (98.0, 1, 8);   -- SatO2
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (15.0, 1, 9);   -- GLASGOW
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (4.0, 1, 10);   -- OCULAR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (5.0, 1, 11);   -- VERBAL
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (6.0, 1, 12);   -- MOTORA
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (15.0, 1, 13);  -- TOTAL
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (2.0, 1, 14);   -- LLENADO_CAPILAR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (2.0, 1, 15);   -- R_PUPILAR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (130.0, 2, 1);  -- PA
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (75.0, 2, 2);   -- PESO
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (165.0, 2, 3);  -- TALLA
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (27.5, 2, 4);   -- IMC
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (80.0, 2, 5);   -- FC
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (20.0, 2, 6);   -- FR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (37.0, 2, 7);   -- T
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (99.0, 2, 8);   -- SatO2
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (14.0, 2, 9);   -- GLASGOW
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (3.0, 2, 10);   -- OCULAR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (4.0, 2, 11);   -- VERBAL
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (5.0, 2, 12);   -- MOTORA
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (12.0, 2, 13);  -- TOTAL
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (3.0, 2, 14);   -- LLENADO_CAPILAR
INSERT INTO atencion_signo (valor_ats, fk_id_atencion_medica, fk_id_signos_vitales) VALUES (3.0, 2, 15);   -- R_PUPILAR


INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Sangre', TRUE, 1);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Radiografía de Tórax', FALSE, 2);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Orina', TRUE, 3);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Electrocardiograma', TRUE, 4);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Glucosa', FALSE, 5);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Tomografía', TRUE, 6);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Ecografía Abdominal', TRUE, 7);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de Función Hepática', FALSE, 8);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de Función Renal', TRUE, 9);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Colesterol', TRUE, 10);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Triglicéridos', FALSE, 11);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Hemoglobina', TRUE, 12);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de Embarazo', TRUE, 13);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de VIH', FALSE, 14);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de Hepatitis', TRUE, 15);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Tiroides', TRUE, 16);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de VDRL', FALSE, 17);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de Esfuerzo', TRUE, 18);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Prueba de Alergias', TRUE, 19);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Creatinina', FALSE, 20);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Bilirrubina', TRUE, 21);
INSERT INTO examen_complementario (titulo_exa, aplica_exa, fk_id_atencion_medica) VALUES ('Examen de Calcio', TRUE, 22);


INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('PIEL Y FANERAS', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('CABEZA', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('CUELLO', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('TÓRAX', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('CORAZÓN', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('ABDOMEN', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('R. INGUINAL', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('M. SUPERIORES', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('M. INFERIORES', NULL, 'N', 1);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('PIEL Y FANERAS', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('CABEZA', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('CUELLO', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('TÓRAX', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('CORAZÓN', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('ABDOMEN', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('R. INGUINAL', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('M. SUPERIORES', NULL, 'N', 2);
INSERT INTO examen_fisico (nombre_exa, numero_exa, descripcion_exa, fk_id_atencion_medica) VALUES ('M. INFERIORES', NULL, 'N', 2);


INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-06-02', FALSE, TRUE, FALSE, 1, 'Cedula 01', 'CodigoMSP 01', 'Entidad Sistema 01', 'Especialidad 01', 'Establecimiento 01', 'Hallazgos 01', 'Institucion 01', 'Nombre Doc 01', 'Resumen 01', 'Servicio 01', 'Servicio Ref 01');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-05-01', TRUE, FALSE, TRUE, 2, 'Cedula 02', 'CodigoMSP 02', 'Entidad Sistema 02', 'Especialidad 02', 'Establecimiento 02', 'Hallazgos 02', 'Institucion 02', 'Nombre Doc 02', 'Resumen 02', 'Servicio 02', 'Servicio Ref 02');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-07-03', FALSE, TRUE, FALSE, 3, 'Cedula 03', 'CodigoMSP 03', 'Entidad Sistema 03', 'Especialidad 03', 'Establecimiento 03', 'Hallazgos 03', 'Institucion 03', 'Nombre Doc 03', 'Resumen 03', 'Servicio 03', 'Servicio Ref 03');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-08-04', TRUE, FALSE, TRUE, 4, 'Cedula 04', 'CodigoMSP 04', 'Entidad Sistema 04', 'Especialidad 04', 'Establecimiento 04', 'Hallazgos 04', 'Institucion 04', 'Nombre Doc 04', 'Resumen 04', 'Servicio 04', 'Servicio Ref 04');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-09-05', FALSE, TRUE, FALSE, 5, 'Cedula 05', 'CodigoMSP 05', 'Entidad Sistema 05', 'Especialidad 05', 'Establecimiento 05', 'Hallazgos 05', 'Institucion 05', 'Nombre Doc 05', 'Resumen 05', 'Servicio 05', 'Servicio Ref 05');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-01', TRUE, TRUE, FALSE, 6, 'Cedula 06', 'CodigoMSP 06', 'Entidad Sistema 06', 'Especialidad 06', 'Establecimiento 06', 'Hallazgos 06', 'Institucion 06', 'Nombre Doc 06', 'Resumen 06', 'Servicio 06', 'Servicio Ref 06');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-02', FALSE, TRUE, TRUE, 7, 'Cedula 07', 'CodigoMSP 07', 'Entidad Sistema 07', 'Especialidad 07', 'Establecimiento 07', 'Hallazgos 07', 'Institucion 07', 'Nombre Doc 07', 'Resumen 07', 'Servicio 07', 'Servicio Ref 07');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-03', TRUE, FALSE, TRUE, 8, 'Cedula 08', 'CodigoMSP 08', 'Entidad Sistema 08', 'Especialidad 08', 'Establecimiento 08', 'Hallazgos 08', 'Institucion 08', 'Nombre Doc 08', 'Resumen 08', 'Servicio 08', 'Servicio Ref 08');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-04', FALSE, TRUE, FALSE, 9, 'Cedula 09', 'CodigoMSP 09', 'Entidad Sistema 09', 'Especialidad 09', 'Establecimiento 09', 'Hallazgos 09', 'Institucion 09', 'Nombre Doc 09', 'Resumen 09', 'Servicio 09', 'Servicio Ref 09');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-05', TRUE, FALSE, TRUE, 10, 'Cedula 10', 'CodigoMSP 10', 'Entidad Sistema 10', 'Especialidad 10', 'Establecimiento 10', 'Hallazgos 10', 'Institucion 10', 'Nombre Doc 10', 'Resumen 10', 'Servicio 10', 'Servicio Ref 10');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-06', FALSE, TRUE, FALSE, 11, 'Cedula 11', 'CodigoMSP 11', 'Entidad Sistema 11', 'Especialidad 11', 'Establecimiento 11', 'Hallazgos 11', 'Institucion 11', 'Nombre Doc 11', 'Resumen 11', 'Servicio 11', 'Servicio Ref 11');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-07', TRUE, FALSE, TRUE, 12, 'Cedula 12', 'CodigoMSP 12', 'Entidad Sistema 12', 'Especialidad 12', 'Establecimiento 12', 'Hallazgos 12', 'Institucion 12', 'Nombre Doc 12', 'Resumen 12', 'Servicio 12', 'Servicio Ref 12');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-08', FALSE, TRUE, FALSE, 13, 'Cedula 13', 'CodigoMSP 13', 'Entidad Sistema 13', 'Especialidad 13', 'Establecimiento 13', 'Hallazgos 13', 'Institucion 13', 'Nombre Doc 13', 'Resumen 13', 'Servicio 13', 'Servicio Ref 13');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-09', TRUE, FALSE, TRUE, 14, 'Cedula 14', 'CodigoMSP 14', 'Entidad Sistema 14', 'Especialidad 14', 'Establecimiento 14', 'Hallazgos 14', 'Institucion 14', 'Nombre Doc 14', 'Resumen 14', 'Servicio 14', 'Servicio Ref 14');
INSERT INTO referencia_medica (fecha_ref, motivo_falta_ref, motivo_limitada_ref, motivo_otros_ref, fk_id_atencion_medica, cedula_doc_ref, codigo_msp_ref, entidad_sistema_ref, especialidad_ref, establecimiento_ref, hallazgos_ref, institucion_ref, nombre_doc_ref, resumen_ref, servicio_ref, servicio_refe_ref) VALUES ('2023-01-10', FALSE, TRUE, FALSE, 15, 'Cedula 15', 'CodigoMSP 15', 'Entidad Sistema 15', 'Especialidad 15', 'Establecimiento 15', 'Hallazgos 15', 'Institucion 15', 'Nombre Doc 15', 'Resumen 15', 'Servicio 15', 'Servicio Ref 15');

 
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE1', 'Diag1', TRUE, 1, 1, 1);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE2', 'Diag2', FALSE, 2, 2, 2);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE3', 'Diag3', TRUE, 3, 3, 3);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE4', 'Diag4', FALSE, 4, 4, 4);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE5', 'Diag5', TRUE, 5, 5, 5);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE6', 'Diag11', TRUE, 1, 6, 6);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE7', 'Diag12', FALSE, 2, 7, 7);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE8', 'Diag13', TRUE, 3, 8, 8);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE9', 'Diag14', FALSE, 4, 9, 9);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE10', 'Diag15', TRUE, 5, 10, 10);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE11', 'Diag6', TRUE, 1, 11, 11);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE12', 'Diag7', FALSE, 2, 12, 12);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE13', 'Diag8', TRUE, 3, 13, 13);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE14', 'Diag9', FALSE, 4, 14, 14);
INSERT INTO diagnostico (codigo_dia, diagnostico_dia, estado_dia, fk_id_atencion_medica, fk_id_enfermedad, fk_id_referencia) VALUES ('CODE15', 'Diag10', TRUE, 5, 15, 15);


INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 12, 'Regular', '28 días', '2023-01-01', true, 3, 1, 0, 1, 0, true, false, '2024-10-01', 'Todos los meses', 'Completa', 'Sin complicaciones', 2);
INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 13, 'Irregular', '35 días', '2023-02-15', true, 2, 2, 1, 0, 1, false, true, '2024-11-01', 'Cada dos meses', 'Incompleta', 'Con algunas complicaciones', 4);
INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 11, 'Regular', '30 días', '2023-03-01', true, 4, 3, 0, 2, 0, true, true, '2024-12-01', 'Cada mes', 'Completa', 'Sin complicaciones', 6);
INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 14, 'Regular', '28 días', '2023-04-01', true, 1, 1, 0, 1, 0, false, false, '2025-01-01', 'Todos los meses', 'Completa', 'Sin complicaciones', 8);
INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 15, 'Irregular', '32 días', '2023-05-01', true, 5, 2, 1, 0, 1, true, true, '2025-02-01', 'Cada dos meses', 'Incompleta', 'Con algunas complicaciones', 10);
INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 12, 'Regular', '30 días', '2023-06-01', true, 3, 1, 0, 1, 0, false, false, '2025-03-01', 'Cada mes', 'Completa', 'Sin complicaciones', 12);
INSERT INTO emergencia_obstetrica (is_embarazada, menarca_eme, ritmo_menstrual_eme, ciclos_eme, fum_eme, ivsa_eme, numero_parejas_sexuales_eme, g_eme, a_eme, p_eme, c_eme, dismenorrea_eme, mastodinia_eme, fpp_eme, controles_eme, inmunizaciones_eme, descripcion_eme, fk_id_ficha_medica) VALUES (TRUE, 13, 'Regular', '28 días', '2023-07-01', true, 2, 2, 1, 0, 1, true, true, '2025-04-01', 'Cada dos meses', 'Completa', 'Sin complicaciones', 14);

INSERT INTO titulo (idTit, contenidoTit, fechaCreacion, leyendaTit, fk_id_instituto) VALUES (1,'Contenido titulo', '1992-01-04', 'Leyenda del título ', 1);







